name: Sync and Fetch ASN MRS Rules

on:
  schedule:
    - cron: '30 18 * * *'  # 北京时间 02:30 执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: meta  # 确保这里是正确的分支
          fetch-depth: 0  # 拉取完整的历史记录，而非浅克隆

      - name: Set Git safe directory
        run: |
          git config --global --add safe.directory /home/runner/work/Rules/Rules

      - name: Create directory for MRS files
        run: |
          mkdir -p rules/IP

      - name: Download .mrs files from MetaCubeX/meta-rules-dat via GitHub API
        run: |
          page=1
          while true; do
            response=$(curl -s "https://api.github.com/repos/MetaCubeX/meta-rules-dat/contents/asn?ref=meta&page=$page&per_page=100")
            echo "API Response (Page $page): $response"

            files_to_download=$(echo "$response" | jq -r '.[].download_url' | grep '\.mrs$')
            if [ -z "$files_to_download" ]; then
              echo "No more .mrs files to download."
              break
            fi

            for url in $files_to_download; do
              echo "Downloading $url"
              curl -sL "$url" -o "rules/IP/$(basename $url)"
            done

            if echo "$response" | grep -q '"next"'; then
              page=$((page + 1))
            else
              break
            fi
          done

      - name: Commit and Push Changes
        run: |
          git add .
          git diff-index --quiet HEAD -- || (git commit -m "Pulled updated MRS files" && git push)