name: Sync and Fetch ASN MRS Rules

on:
  schedule:
    - cron: '30 18 * * *'  # 北京时间 02:30 执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  pull-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: meta  # 检出 meta 分支

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create directory for MRS files
        run: |
          mkdir -p rules/IP

      - name: Download .mrs files from MetaCubeX/meta-rules-dat
        run: |
          # 页数初始化
          page=1
          while true; do
            # 获取指定目录的内容
            response=$(curl -s "https://api.github.com/repos/MetaCubeX/meta-rules-dat/contents/asn?ref=meta&page=$page&per_page=100")
            echo "API Response (Page $page): $response"
            
            # 检查是否包含错误信息
            if echo "$response" | grep -q '"message": "Not Found"'; then
              echo "The specified directory does not exist or the ref is invalid."
              exit 1
            fi

            # 处理 API 响应并下载 .mrs 文件
            # 获取文件的 download_url
            files_to_download=$(echo "$response" | grep -o '"download_url": *"[^"]*' | grep -o '[^"]*$' | grep '\.mrs$')
            if [ -z "$files_to_download" ]; then
              echo "No more .mrs files to download."
              break
            fi

            # 下载文件
            for url in $files_to_download; do
              echo "Downloading $url"
              curl -sL "$url" -o "rules/IP/$(basename $url)"
            done

            # 如果有更多页面，继续下一页
            if echo "$response" | grep -q '"next"'; then
              page=$((page + 1))
            else
              break
            fi
          done

      - name: Commit and Push Changes
        run: |
          git add .
          git diff-index --quiet HEAD -- || (git commit -m "Pulled updated MRS files" && git push)