name: Sync and Compile BanAd Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 北京时间 02:00 执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  banad_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch BanAd Rules
      run: |
        mkdir -p rules/Domain  # 确保目录存在

        # 下载 BanAd 规则文件
        curl -sL "https://raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/qx.list" -o rules/Domain/banad.list

    - name: Convert BanAd Rules to YAML
      run: |
        echo "payload:" > rules/Domain/banad_combined.yaml
        grep '^DOMAIN,' rules/Domain/banad.list | sed 's/,reject//' | cut -d',' -f2 | while read -r domain; do
          echo "  - $domain" >> rules/Domain/banad_combined.yaml
        done

    - name: Convert BanAd Rules to MRS
      run: |
        mihomo convert-ruleset domain yaml rules/Domain/banad_combined.yaml rules/Domain/banAd.mrs
        rm -f rules/Domain/banad.list rules/Domain/banad_combined.yaml

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated BanAd rules (qx.list -> banAd.mrs)" && git push)
