name: Sync and Compile Ad Blocking Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 每天北京时间02:00执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  ban_ad_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch Ad Blocking Rules
      run: |
        mkdir -p rules/Domain  # 确保目录存在

        # 下载广告拦截规则文件
        curl -sL "https://raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/qx.list" -o rules/qx.list

    - name: Extract DOMAIN rules
      run: |
        # 提取 DOMAIN 和 DOMAIN-SUFFIX 规则
        grep -E 'DOMAIN|DOMAIN-SUFFIX' rules/qx.list > rules/Domain/banAd.list

    - name: Convert DOMAIN rules to YAML
      run: |
        # 将 DOMAIN 和 DOMAIN-SUFFIX 规则转换为 YAML 格式
        echo "payload:" > rules/Domain/banAd.yaml
        while IFS=, read -r type domain; do
          if [[ -n "$domain" && ! "$domain" =~ ^# ]]; then
            echo "  - $domain" >> rules/Domain/banAd.yaml
          fi
        done < rules/Domain/banAd.list

    - name: Convert DOMAIN rules to MRS
      run: |
        # 使用 mihomo 转换为 MRS 格式，并命名为 banAd.mrs
        mihomo convert-ruleset domain yaml rules/Domain/banAd.yaml rules/Domain/banAd.mrs

    - name: Clean up temporary files
      run: |
        # 删除临时文件
        rm -f rules/qx.list rules/Domain/banAd.list rules/Domain/banAd.yaml

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated Ad Blocking rules -> banAd.mrs" && git push)