name: Sync and Compile Direct Rules to MRS

on:
  schedule:
    - cron: '0 18 * * *'  # 每天北京时间02:00执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  direct_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch Direct Rules
      run: |
        mkdir -p rules/Domain  # 确保目录存在

        # 下载 Direct 规则文件
        curl -sL "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/direct.list" -o rules/Domain/direct.list

    - name: Convert Direct Rules to YAML
      run: |
        echo "payload:" > rules/Domain/direct_combined.yaml
        while IFS=, read -r type value; do
          if [[ -n "$type" && -n "$value" ]]; then
            echo "  - $value" >> rules/Domain/direct_combined.yaml
          fi
        done < rules/Domain/direct.list

    - name: Convert Direct Rules to MRS
      run: |
        # 使用 mihomo 转换为 MRS 格式
        mihomo convert-ruleset domain yaml rules/Domain/direct_combined.yaml rules/Domain/direct.mrs

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated Direct rules (direct.list -> direct.mrs)" && git push)
