name: Sync and Compile Emby Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 北京时间 02:00 执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  emby_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch and Merge Emby Rules
      run: |
        mkdir -p rules/Domain  # 确保目录存在

        # 下载 Emby 规则文件
        curl -sL "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/emby.list" -o rules/Domain/emby1.list
        curl -sL "https://raw.githubusercontent.com/666OS/YYDS/main/mihomo/rules/emby.list" -o rules/Domain/emby2.list

        # 合并去重
        cat rules/Domain/emby1.list rules/Domain/emby2.list | grep -v '^#' | sort -u > rules/Domain/merged_emby.list

    - name: Extract and Format DOMAIN and DOMAIN-SUFFIX rules
      run: |
        # 提取并格式化 DOMAIN 和 DOMAIN-SUFFIX 规则
        echo "payload:" > rules/Domain/emby.yaml

        # 处理 DOMAIN-SUFFIX 和 DOMAIN 规则
        grep -E '^DOMAIN-SUFFIX,[^,]+' rules/Domain/merged_emby.list | sed 's/^DOMAIN-SUFFIX,/+. /' >> rules/Domain/emby.yaml
        grep -E '^DOMAIN,[^,]+' rules/Domain/merged_emby.list | sed 's/^DOMAIN,//' >> rules/Domain/emby.yaml

    - name: Convert Emby Rules to MRS
      run: |
        # 使用 mihomo 转换为 MRS 格式
        mihomo convert-ruleset domain yaml rules/Domain/emby.yaml rules/Domain/emby.mrs

    - name: Clean up the source files
      run: |
        # 删除源文件
        rm -f rules/Domain/emby1.list rules/Domain/emby2.list rules/Domain/merged_emby.list

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated emby rules (merged emby.list -> emby.mrs)" && git push)