name: Sync and Convert Game Rules to MRS

on:
  schedule:
    - cron: '0 1 * * 1'  # 每周一 UTC 时间 01:00 执行（北京时间 09:00）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  game_rules_to_mrs:
    runs-on: ubuntu-latest

    steps:
    - name: 检出代码仓库
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: 设置 Git 用户信息
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: 安装 mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: 清理规则文件，去除多余空格和换行符
      run: |
        # 遍历 rules/Game 目录下的所有 YAML 文件
        for file in rules/Game/*.yaml; do
          # 使用 sed 删除文件开头和结尾的空白字符
          sed -i 's/^[[:space:]]*//;s/[[:space:]]*$//' "$file"
        done

    - name: 将所有游戏规则 YAML 转换为 MRS 格式
      run: |
        # 遍历 rules/Game 目录下的所有 YAML 文件
        for file in rules/Game/*.yaml; do
          filename=$(basename -- "$file")
          name="${filename%.yaml}"
          output="rules/Game/${name}.mrs"

          # 使用 mihomo 将 YAML 转换为 MRS 格式
          if ! mihomo convert-ruleset ipcidr yaml "$file" "$output"; then
            echo "转换失败：$file"
            exit 1
          fi
        done

    - name: 提交并推送更改
      run: |
        git add .
        if git diff-index --quiet HEAD --; then
          echo "没有需要提交的更改"
        else
          git commit -m "将游戏规则转换为 MRS 格式"
          git push
        fi