name: Sync and Convert Game Rules to MRS

on:
  schedule:
    - cron: '0 1 * * 1'  # 每周一 UTC 01:00（北京时间09:00）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies and mihomo
        run: |
          sudo apt-get update
          sudo apt-get install -y jq perl
          # 下载并安装 mihomo
          version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
          curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | gunzip -c > mihomo
          chmod +x mihomo
          sudo mv mihomo /usr/local/bin/

      - name: Create temporary folder for YAML files
        run: |
          mkdir -p rules/Game/action2

      - name: Download YAML files via GitHub API
        run: |
          cd rules/Game/action2
          # 使用 GitHub API 获取 rules/Game 目录下所有 YAML 文件的下载链接
          files=$(curl -s "https://api.github.com/repos/Lanlan13-14/Rules/contents/rules/Game?ref=main" | jq -r '.[].download_url' | grep '\.yaml$')
          for url in $files; do
            echo "Downloading $url"
            curl -sL "$url" -O
          done
          cd -

      - name: Move downloaded YAML files to main folder
        run: |
          # 将临时目录中的 YAML 文件移动到 rules/Game 目录中（保留原始 YAML 文件）
          mv rules/Game/action2/*.yaml rules/Game/

      - name: Process and convert each YAML file
        run: |
          # 遍历 rules/Game 目录下所有 YAML 文件（临时目录中的文件已移动）
          for file in rules/Game/*.yaml; do
            echo "Processing file: $file"
            # 使用 Perl 清除单引号内前后多余空格
            # 例如将 "- '1.201.188.0/23 '" 转换为 "- '1.201.188.0/23'"
            perl -i -pe "s/'\s*([^']*?)\s*'/'\$1'/g" "$file"
            base=$(basename "$file" .yaml)
            output="rules/Game/${base}.mrs"
            echo "Converting $file to $output"
            mihomo convert-ruleset ipcidr yaml "$file" "$output"
          done

      - name: Remove temporary folder
        run: |
          rm -rf rules/Game/action2

      - name: Commit and Push Changes
        run: |
          git add .
          git diff-index --quiet HEAD -- || (git commit -m "Converted game rules to MRS format" && git push)