name: Sync and Convert Game Rules

on:
  schedule:
    - cron: '0 0 * * 1'  # 每周一 00:00 UTC（北京时间 08:00）执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  game_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create action directory
      run: mkdir -p rules/Game/action

    - name: Fetch Game Rules
      run: |
        # 克隆 SSTap-Rule 仓库，仅拉取 rules 目录
        git clone --depth=1 --filter=blob:none --sparse https://github.com/FQrabbit/SSTap-Rule.git tmp_repo
        cd tmp_repo
        git sparse-checkout set rules
        cp -r rules/* ../rules/Game/action/
        cd ..
        rm -rf tmp_repo

    - name: Convert Rules to YAML
      run: |
        mkdir -p rules/Game
        for file in rules/Game/action/*.rules; do
          filename=$(basename -- "$file")
          name="${filename%.rules}"
          output="rules/Game/${name}.yaml"

          echo "payload:" > "$output"
          grep -v '^#' "$file" | awk '{if (NF > 0) print "  - \x27"$0"\x27"}' >> "$output"
        done

    - name: Remove Action Folder
      run: rm -rf rules/Game/action

    - name: Pull Latest Changes from Remote
      run: |
        git pull origin main

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated game rules" && git push)