name: Sync and Compile Google Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 每天北京时间02:00执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  google_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch Google Rules
      run: |
        mkdir -p rules/Domain  # 确保目录存在
        curl -sL "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/google-play.list" -o rules/Domain/google-play.yaml
        curl -sL "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/google.yaml" -o rules/Domain/google.yaml

    - name: Merge and Remove Duplicates from YAML Files
      run: |
        cat rules/Domain/google.yaml rules/Domain/google-play.yaml | \
        sort -u > rules/Domain/google-merged.yaml

    - name: Convert Google Rules to MRS
      run: |
        mihomo convert-ruleset domain yaml rules/Domain/google-merged.yaml rules/Domain/google.mrs

    - name: Clean up temporary files
      run: |
        rm -f rules/Domain/google.yaml rules/Domain/google-play.yaml rules/Domain/google-merged.yaml

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated Google rules -> google.mrs" && git push)
