name: Sync and Compile Proxymini Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 北京时间 02:00 执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  proxy_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch Proxymini Rules
      run: |
        mkdir -p rules/Domain  # 确保目录存在

        # 下载 Proxymini 规则文件
        curl -sL "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/Proxymini.list" -o rules/Domain/proxymini.list

    - name: Convert Proxymini Rules to YAML
      run: |
        echo "payload:" > rules/Domain/proxymini_combined.yaml
        while IFS=, read -r type value; do
          if [[ -n "$type" && -n "$value" ]]; then
            echo "  - $type,$value" >> rules/Domain/proxymini_combined.yaml
          fi
        done < rules/Domain/proxymini.list

    - name: Convert Proxymini Rules to MRS
      run: |
        mihomo convert-ruleset domain yaml rules/Domain/proxymini_combined.yaml rules/Domain/proxy.mrs
        rm -f rules/Domain/proxymini.list rules/Domain/proxymini_combined.yaml

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated Proxymini rules (Proxymini.list -> proxy.mrs)" && git push)
