name: Sync and Compile Proxymini Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 北京时间 02:00 执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  proxy_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch Proxymini Rules
      run: |
        mkdir -p rules/Domain  # 确保目录存在

        # 下载 Proxymini 规则文件
        curl -sL "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/Proxymini.list" -o rules/Domain/proxymini.list

    - name: Extract DOMAIN and DOMAIN-SUFFIX rules from proxymini.list
      run: |
        # 提取 DOMAIN 和 DOMAIN-SUFFIX 规则，并过滤掉以 # 开头的注释行
        grep -E '^(DOMAIN-SUFFIX|DOMAIN),' rules/Domain/proxymini.list | sed -E 's/DOMAIN-SUFFIX,/*./g; s/DOMAIN,//g' > rules/Domain/proxymini-domain.list

    - name: Convert Proxymini Rules to YAML
      run: |
        echo "payload:" > rules/Domain/proxy.yaml
        sort -u rules/Domain/proxymini-domain.list | awk '{print "  - \047" $0 "\047"}' >> rules/Domain/proxy.yaml

    - name: Convert Proxymini Rules to MRS
      run: |
        # 使用 mihomo 转换为 MRS 格式
        mihomo convert-ruleset domain yaml rules/Domain/proxy.yaml rules/Domain/proxy.mrs
        rm -f rules/Domain/proxymini-domain.list rules/Domain/proxymini.list

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated Proxymini rules (Proxymini.list -> proxy.mrs)" && git push)