name: Sync and Compile WeChat Rules

on:
  schedule:
    - cron: '0 18 * * *'  # 每天北京时间02:00执行
  workflow_dispatch:

permissions:
  contents: write

jobs:
  wechat_rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Git user
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Install mihomo
      run: |
        version=$(curl -sL https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/version.txt)
        curl -sL "https://github.com/MetaCubeX/mihomo/releases/download/Prerelease-Alpha/mihomo-linux-amd64-${version}.gz" | \
          gunzip -c > /usr/local/bin/mihomo && chmod +x /usr/local/bin/mihomo

    - name: Fetch WeChat Rules
      run: |
        mkdir -p rules/WeChat  # 确保目录存在
        curl -sL "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/WeChat/WeChat.list" -o rules/WeChat/WeChat.list

    - name: Extract DOMAIN rules from WeChat.list
      run: |
        # 提取 WeChat.list 中的 DOMAIN-SUFFIX 和 DOMAIN 规则
        grep -Eo 'DOMAIN-SUFFIX,[^,]+' rules/WeChat/WeChat.list | sed 's/DOMAIN-SUFFIX,//' > rules/WeChat/WeChat-domain.list
        grep -Eo 'DOMAIN,[^,]+' rules/WeChat/WeChat.list | sed 's/DOMAIN,//' >> rules/WeChat/WeChat-domain.list

    - name: Format extracted domains as YAML
      run: |
        echo "payload:" > rules/WeChat/WeChat.yaml
        sort -u rules/WeChat/WeChat-domain.list | awk '{print "  - \047" $0 "\047"}' >> rules/WeChat/WeChat.yaml

    - name: Convert WeChat DOMAIN rules to MRS
      run: |
        # 使用 mihomo 转换为 MRS 格式
        mihomo convert-ruleset domain yaml rules/WeChat/WeChat.yaml rules/WeChat/WeChat.mrs

    - name: Clean up temporary files
      run: |
        rm -f rules/WeChat/WeChat.list rules/WeChat/WeChat-domain.list rules/WeChat/WeChat.yaml

    - name: Commit and Push Changes
      run: |
        git add .
        git diff-index --quiet HEAD -- || (git commit -m "Updated WeChat rules -> WeChat.mrs" && git push)